- index.json
- lib/check-or-update-webhooks.js
- lib/section-to-webhook.js
> remove obsolete events

- index.json
- lib/check-or-update-webhooks.js
- lib/section-to-webhook.js
- lib/workarounds.js
closes #4 with some workarounds
> missing actions

- index.json
- lib/section-to-webhook.js
- lib/workarounds.js
> Add "synchronize" action for "pull_request" event

- lib/create-pr-on-change.js
- lib/get-html.js
- package-lock.json
- package.json
> Greenkeeper/@octokit/request 4.0.1

- package.json
This is a tiny PR to get my feet wet with this project.
- add a `description` to package.json, borrowing from the README
- simplify the `repository` value in package.json to an HTTP string
> docs: update package.json

- index.json
- lib/check-or-update-webhooks.js
- lib/section-to-webhook.js
- lib/workarounds.js
- package-lock.json
- package.json
- schema.js
- test.js
This PR updates the build process to extract descriptions from the events listed at https://developer.github.com/v3/activity/events/types/
Notes:
- Supports multi-paragraph descriptions
- HTML is converted to Markdown using `turndown`, following prior art from other Octokit projects
- Links to `/v3` are rewritten as fully-qualified `developer.github.com` URLs
- Introduced a basic JSON schema and added `ajv` to validate the shape of each extracted webhook object.
- I refactored `section-to-webhook.js` to make it easier to read and refine. I was also able to remove some workarounds around quoted action names that were no longer necessary.
- Removed the workaround for `pull_request.synchronize` which is no longer needed.
cc @rachmari @sarahs @bswinnerton @jasonetco
Resolves #89
> feat: event descriptions

- cache/webhook-events-and-payloads.html
- lib/get-html.js
> build: only cache relevant HTML

- CONTRIBUTING.md
follow up https://github.com/octokit/webhooks/pull/180#issuecomment-703803749, thank you @christophehurpeau
> docs(CONTRIBUTING): Adding examples

- cache/webhook-events-and-payloads.html
- lib/get-html.js
- lib/get-sections.js
fixes problem that causes the update workflow to fail: https://github.com/octokit/webhooks/runs/1221937836
> build: "Make a contribution" link is not part of table of contents

- .github/ISSUE_TEMPLATES/01_help.md
- .github/ISSUE_TEMPLATES/02_bug.md
- .github/ISSUE_TEMPLATES/03_feature_request.md
- .github/ISSUE_TEMPLATES/04_thanks.md
Add issue templates to repository
Fix #191 
Relates to https://github.com/octokit/webhooks.js/issues/305
> docs(issue-templates): add issue templates to repository

- index.json
- payload-examples/api.github.com/project_card/created.payload.json
- payload-examples/api.github.com/project_card/created.with-installation.payload.json
- payload-examples/api.github.com/project_card/created.with-organization.payload.json
- payload-examples/api.github.com/project_card/deleted.payload.json
- payload-examples/api.github.com/project_card/deleted.with-installation.payload.json
- payload-examples/api.github.com/project_card/deleted.with-organization.payload.json
- payload-schemas/schemas/project_card/converted.schema.json
- payload-schemas/schemas/project_card/created.schema.json
- payload-schemas/schemas/project_card/deleted.schema.json
- payload-schemas/schemas/project_card/edited.schema.json
- payload-schemas/schemas/project_card/moved.schema.json
> fix: Add the `content_url` property to `project_card` events

- .github/workflows/update.yml
Addresses https://github.com/octokit/webhooks/pull/262\#issuecomment-758267747
> ci(update): use `npm` script

- payload-schemas/schemas/issues/assigned.schema.json
- payload-schemas/schemas/issues/closed.schema.json
- payload-schemas/schemas/issues/deleted.schema.json
- payload-schemas/schemas/issues/demilestoned.schema.json
- payload-schemas/schemas/issues/edited.schema.json
- payload-schemas/schemas/issues/labeled.schema.json
- payload-schemas/schemas/issues/locked.schema.json
- payload-schemas/schemas/issues/milestoned.schema.json
- payload-schemas/schemas/issues/opened.schema.json
- payload-schemas/schemas/issues/pinned.schema.json
- payload-schemas/schemas/issues/reopened.schema.json
- payload-schemas/schemas/issues/transferred.schema.json
- payload-schemas/schemas/issues/unassigned.schema.json
- payload-schemas/schemas/issues/unlabeled.schema.json
- payload-schemas/schemas/issues/unlocked.schema.json
Turns out there are more of these 🤷
> fix: don't validate array as a tuple (again)

- bin/octokit-schema.ts
- package.json
- payload-schemas/schemas/common/asset.schema.json
- payload-schemas/schemas/release/created.schema.json
- payload-schemas/schemas/release/deleted.schema.json
- payload-schemas/schemas/release/edited.schema.json
- payload-schemas/schemas/release/prereleased.schema.json
- payload-schemas/schemas/release/published.schema.json
- payload-schemas/schemas/release/released.schema.json
- payload-schemas/schemas/release/unpublished.schema.json
- schema.d.ts
This also brings with it support for referencing common schemas from other common schemas 🎉
> refactor: create `asset` common schema

- .github/workflows/update.yml
addresses https://github.com/octokit/webhooks/pull/285#issuecomment-761236156
> ci(update): update schema and types on changes from scraping the webhooks documentation

- payload-schemas/schemas/check_run/completed.schema.json
- payload-schemas/schemas/check_run/created.schema.json
- payload-schemas/schemas/check_run/requested_action.schema.json
- payload-schemas/schemas/check_run/rerequested.schema.json
- payload-schemas/schemas/check_suite/completed.schema.json
- payload-schemas/schemas/check_suite/requested.schema.json
- payload-schemas/schemas/check_suite/rerequested.schema.json
- payload-schemas/schemas/installation/created.schema.json
- payload-schemas/schemas/installation/deleted.schema.json
- payload-schemas/schemas/installation/new_permissions_accepted.schema.json
- payload-schemas/schemas/installation/suspended.schema.json
- payload-schemas/schemas/installation/unsuspended.schema.json
- payload-schemas/schemas/installation_repositories/added.schema.json
- payload-schemas/schemas/installation_repositories/removed.schema.json
- payload-schemas/schemas/integration_installation/created.schema.json
- payload-schemas/schemas/integration_installation_repositories/added.schema.json
- schema.d.ts
This adds types to array items where the type is known
> fix: add types for items in arrays

- payload-schemas/schemas/code_scanning_alert/appeared_in_branch.schema.json
- payload-schemas/schemas/code_scanning_alert/closed_by_user.schema.json
- payload-schemas/schemas/code_scanning_alert/created.schema.json
- payload-schemas/schemas/code_scanning_alert/fixed.schema.json
- payload-schemas/schemas/code_scanning_alert/reopened.schema.json
- payload-schemas/schemas/code_scanning_alert/reopened_by_user.schema.json
- payload-schemas/schemas/workflow_dispatch/event.schema.json
- payload-schemas/schemas/workflow_run/completed.schema.json
- payload-schemas/schemas/workflow_run/requested.schema.json
- schema.d.ts
Remove properties from `required` that are optional, and removes some all together when that property isn't present
> fix: adjust required properties

- bin/ref-common-schemas.ts
> chore: normalize references to common schemas when searching for refs

- payload-schemas/schemas/installation/suspend.schema.json
- payload-schemas/schemas/installation/unsuspend.schema.json
- schema.d.ts
suspended -> suspend
unsuspended -> unsuspend
> fix: installation actions

- index.json
- payload-examples/api.github.com/pull_request_review/submitted.payload.json
- payload-examples/api.github.com/pull_request_review/submitted.with-organization.payload.json
- payload-schemas/schemas/pull_request_review/submitted.schema.json
- schema.d.ts
> fix: add missing properties to pull_request_review.submitted 

- payload-schemas/schemas/installation/suspend.schema.json
- payload-schemas/schemas/installation/unsuspend.schema.json
- schema.d.ts
> fix: name of `installation` `suspend` & `unsuspend` action schemas

- bin/validate-payload-examples.ts
Brought this over from my azure function
> chore: improve printing of validate errors when validating payloads

- bin/ref-common-schemas.ts
- payload-schemas/schemas/common/link.schema.json
- payload-schemas/schemas/common/pull-request.schema.json
- payload-schemas/schemas/common/simple-pull-request.schema.json
- payload-schemas/schemas/pull_request/closed.schema.json
- payload-schemas/schemas/pull_request/converted_to_draft.schema.json
- payload-schemas/schemas/pull_request/opened.schema.json
- payload-schemas/schemas/pull_request/ready_for_review.schema.json
- payload-schemas/schemas/pull_request/reopened.schema.json
- payload-schemas/schemas/pull_request_review/dismissed.schema.json
- payload-schemas/schemas/pull_request_review/edited.schema.json
- payload-schemas/schemas/pull_request_review/submitted.schema.json
- payload-schemas/schemas/pull_request_review_comment/created.schema.json
- payload-schemas/schemas/pull_request_review_comment/deleted.schema.json
- payload-schemas/schemas/pull_request_review_comment/edited.schema.json
- schema.d.ts
It's a small one, but still nice to have since they should all be the same format etc
> feat: create `Link` interface

- bin/format-with-prettier.ts
- payload-examples/api.github.com/check_run/requested_action.payload.json
- payload-examples/api.github.com/pull_request_review_comment/edited.payload.json
- payload-schemas/schemas/common/app.schema.json
- payload-schemas/schemas/common/label.schema.json
- payload-schemas/schemas/common/release-asset.schema.json
(this is more about fixing the bug in the script than anything else 😅)
> chore: format json files with prettier

- bin/optimize-schemas.ts
- payload-schemas/schemas/check_run/completed.schema.json
- payload-schemas/schemas/check_run/rerequested.schema.json
- payload-schemas/schemas/code_scanning_alert/reopened_by_user.schema.json
- payload-schemas/schemas/installation_repositories/added.schema.json
(mainly just adding the support for new things so it doesn't crash)
> fix: optimize schemas

- package-lock.json
- package.json
as talked about [here](https://github.com/octokit/webhooks/pull/254#pullrequestreview-564647988).
> chore: add `prettier-plugin-packagejson`

- index.json
- lib/check-or-update-webhooks.ts
- lib/section-to-webhook.ts
- lib/types.ts
This is a simple addition that can help in updating schemas automatically with new docs updates
> feat: add properties to index.json

- index.json
- lib/section-to-webhook.ts
Not all of the first table rows are for the `action` property.
instead, filter it out by name
> fix: add missing properties

- payload-schemas/schemas/code_scanning_alert/appeared_in_branch.schema.json
- payload-schemas/schemas/code_scanning_alert/closed_by_user.schema.json
- payload-schemas/schemas/code_scanning_alert/created.schema.json
- payload-schemas/schemas/code_scanning_alert/fixed.schema.json
- payload-schemas/schemas/code_scanning_alert/reopened.schema.json
- payload-schemas/schemas/code_scanning_alert/reopened_by_user.schema.json
- payload-schemas/schemas/common/alert-instance.schema.json
- schema.d.ts
> refactor: create AlertInstance schema for CodeScaningAlertEvent#alert#instances

- index.json
- payload-examples/api.github.com/pull_request/assigned.payload.json
- payload-examples/api.github.com/pull_request/assigned.with-organization.payload.json
- payload-examples/api.github.com/pull_request/closed.payload.json
- payload-examples/api.github.com/pull_request/closed.with-organization.payload.json
- payload-examples/api.github.com/pull_request/converted_to_draft.payload.json
- payload-examples/api.github.com/pull_request/converted_to_draft.with-installation.payload.json
- payload-examples/api.github.com/pull_request/converted_to_draft.with-organization.payload.json
- payload-examples/api.github.com/pull_request/labeled.payload.json
- payload-examples/api.github.com/pull_request/labeled.with-organization.payload.json
- payload-examples/api.github.com/pull_request/locked.payload.json
- payload-examples/api.github.com/pull_request/locked.with-organization.payload.json
- payload-examples/api.github.com/pull_request/opened.payload.json
- payload-examples/api.github.com/pull_request/opened.with-organization.payload.json
- payload-examples/api.github.com/pull_request/ready_for_review.payload.json
- payload-examples/api.github.com/pull_request/ready_for_review.with-installation.payload.json
- payload-examples/api.github.com/pull_request/ready_for_review.with-organization.payload.json
- payload-examples/api.github.com/pull_request/reopened.payload.json
- payload-examples/api.github.com/pull_request/reopened.with-organization.payload.json
- payload-examples/api.github.com/pull_request/review_request_removed.payload.json
- payload-examples/api.github.com/pull_request/review_requested.payload.json
- payload-examples/api.github.com/pull_request/unassigned.payload.json
- payload-examples/api.github.com/pull_request/unassigned.with-organization.payload.json
- payload-examples/api.github.com/pull_request/unlabeled.payload.json
- payload-examples/api.github.com/pull_request/unlabeled.with-organization.payload.json
- payload-examples/api.github.com/pull_request/unlocked.payload.json
- payload-examples/api.github.com/pull_request/unlocked.with-organization.payload.json
- payload-schemas/schemas/common/pull-request.schema.json
- schema.d.ts
I've only ever seen this as `null` so far, but expect it can be another type - I'd assume `boolean` but it might not be 🤷
> fix: add `auto_merge` property to `PullRequest` interface

- index.json
- payload-examples/api.github.com/workflow_run/completed.payload.json
- payload-schemas/schemas/common/workflow-run.schema.json
- schema.d.ts
>  fix: add `check_suite_id` property to `WorkflowRun` interface

- payload-schemas/schemas/workflow_run/completed.schema.json
- payload-schemas/schemas/workflow_run/requested.schema.json
- schema.d.ts
> fix: improve type of `WorkflowRun#conclusion` property

- payload-examples/api.github.com/code_scanning_alert/closed-by-user.payload.json
- payload-examples/api.github.com/code_scanning_alert/created.payload.json
- payload-examples/api.github.com/code_scanning_alert/fixed.payload.json
- payload-examples/api.github.com/project_card/moved.payload.json
- payload-schemas/schemas/common/alert-instance.schema.json
- payload-schemas/schemas/workflow_run/completed.schema.json
- payload-schemas/schemas/workflow_run/requested.schema.json
There are some digressions between the regular prettier lint script and the bin script
> lint: run formatter script

- .github/workflows/test.yml
- package-lock.json
- package.json
- payload-examples/index.d.ts
- payload-examples/package-lock.json
- payload-examples/package.json
Release went smoothly with no issues
> fix: update `d.ts` for `payload-examples` to match the JSON

- payload-schemas/api.github.com/common/commit.schema.json
- payload-schemas/api.github.com/common/installation.schema.json
- payload-schemas/api.github.com/member/added.schema.json
- payload-schemas/api.github.com/repository/edited.schema.json
- payload-schemas/api.github.com/repository_vulnerability_alert/resolve.schema.json
- payload-types/schema.d.ts
> Schema updates

- payload-schemas/api.github.com/check_run/completed.schema.json
- payload-schemas/api.github.com/check_run/created.schema.json
- payload-schemas/api.github.com/check_run/requested_action.schema.json
- payload-schemas/api.github.com/check_run/rerequested.schema.json
- payload-schemas/api.github.com/common/deployment-workflow-run.schema.json
- payload-schemas/api.github.com/common/deployment.schema.json
- payload-schemas/api.github.com/deployment/created.schema.json
- payload-schemas/api.github.com/deployment_status/created.schema.json
- payload-types/schema.d.ts
These changes are related to recent changes to the GitHub pages build process to provide more insight into why pages failed to build.
> feat: updates to `deployment` and `deployment_status` events, new `deployment` property for `check_run` event

- .github/workflows/update.yml
https://github.com/octokit/webhooks/pull/691#issuecomment-1211018063
> ci(update): add notes to PR body about modifying schemas

- payload-examples/api.github.com/organization/renamed.payload.json
- payload-examples/api.github.com/workflow_job/completed.failure.with-organization.payload.json
- payload-examples/api.github.com/workflow_job/completed.success.with-organization.payload.json
- payload-examples/api.github.com/workflow_job/in_progress.payload.json
- payload-examples/api.github.com/workflow_job/queued.payload.json
- payload-schemas/api.github.com/common/app.schema.json
- payload-schemas/api.github.com/common/installation.schema.json
- payload-schemas/api.github.com/common/repository.schema.json
- payload-schemas/api.github.com/common/workflow-job.schema.json
- payload-schemas/api.github.com/organization/renamed.schema.json
- payload-types/schema.d.ts
Assorted fixes I have collected from my app webhooks, and validated against this repo
> feat: schema updates to `workflow_job`, `organization.renamed` events and common schemas

- .github/pull_request_template.md
- .github/workflows/codeql-analysis.yml
- .github/workflows/prettier.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .github/workflows/update.yml
- CONTRIBUTING.md
- package.json
This changes the default branch from master --> main across the repository content to match the state of the repository settings. 
----
* Links, Actions, and references used the "master" default branch name. 
* Links, Actions, and references use the "main" default branch name
If `Yes`, what's the impact:  
* N/A
Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`
----
> Default branch rename

- payload-schemas/api.github.com/installation_target/renamed.schema.json
- payload-types/schema.d.ts
----
* `installation_target` event was not documented in this repo
* The event is now documented in this repo
*
----
Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/main/community/breaking_changes.md) to help!
If `Yes`, what's the impact:
* N/A
Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`
----
> feat: new `installation_target` event

- payload-schemas/api.github.com/secret_scanning_alert_location/created.schema.json
- payload-types/schema.d.ts
…
----
* The `action` property wasn't set as required and thus was generating as potentially `undefined`
* Marks the `action` property as required
*
----
Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/main/community/breaking_changes.md) to help!
If `Yes`, what's the impact:
* N/A
Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
----
> fix: mark `action` as required in `secret_scanning_alert_location.created` event

- payload-examples/package.json
Adds the github enterprise server directories to the package export
----
* 
* 
----
> feat(examples): add GitHub Enterprise Server versions

- .github/workflows/prettier.yml
- bin/diff-interface-schemas.mts
- bin/extract-common-schema.mts
- bin/format-with-prettier.mts
- bin/octokit-schema.mts
- bin/octokit-types.mts
- bin/octokit-webhooks.mts
- bin/optimize-schemas.mts
- bin/ref-common-schemas.mts
- bin/validate-schema.mts
- package.json
----
* Some scripts were broken after #845, some updates were missed
* All scripts should be functional
----
> build: fix scripts that were broken due to transition to ESM

- .github/workflows/update.yml
----
* The workflow would run every hour, and would end up generating notifications because of new cache updates
* Reduce the workflow to every 12 hours
----
> workflow(update): reduce execution time to once per 12 hours

- .github/workflows/test.yml
----
* ❌ `@github-actions` Test / test (pull_request) Failing after 1m
* ✅ `@github-actions` Test / test (pull_request) Successful in 15s
* The two jobs have distinct names
----
> Disambiguate test jobs

- bin/format-with-prettier.mts
----
* The "Lint repository contents" action fails executing this script
* The "Lint repository contents" action shouldn't fail executing this script
----
> build: fix prettier script

- .github/workflows/release.yml
- package.json
- payload-examples/package.json
- payload-schemas/package.json
- payload-types/package.json
This enables provenance. Please note that this PR was created automatically (using Octokit), so it may not be perfect.
> feat(security): Add provenance

- payload-schemas/api.github.com/branch_protection_configuration/disabled.schema.json
- payload-schemas/api.github.com/branch_protection_configuration/enabled.schema.json
> fix(schema): correct some schema IDs
