package.json

To publish `index.d.ts` on future releases of this package.
To have types of webhook examples available when consuming this package with TypeScript.
After adding `index.d.ts` file (77c7cd49a08bfb917ed4bd74364de866351e13f6), it was not added to be published.

👷 build(package): publish types on releases of this package

---

index.json
lib/get-ping-webhook.js

Replace `"example"` property for `"examples"` on `ping` webhook
To have consistency between properties on each webhook for [TypeScript migration](https://github.com/octokit/webhooks.js/pull/113)
* TypeScript migration: https://github.com/octokit/webhooks.js/pull/113

📦 refactor(ping-webhook): replace 'example' for 'examples' for consistency with the resto webhooks

---

index.d.ts

- Export `type WebhookDefinition` for usage on third party projects
* [This migration](https://github.com/octokit/webhooks.js/pull/113) needs WebhookDefinition types exposed.
* Blocked by https://github.com/octokit/webhooks/pull/82 to avoid problems of `examples` 🆚 `example` property on `type WebhookDefinition`
* TypeScript migration of webhooks.js: https://github.com/octokit/webhooks.js/pull/113

🐛 fix(type-declaration): export WebhookDefinition type for external usage

---

cache/event-types-and-payloads.html
index.json
lib/workarounds.js

This PR removes a workaround, now that the issue has been resolved on GitHub's side.
```
$ ./bin/octokit-webhooks.js check         
⌛  fetching https://developer.github.com/v3/activity/events/types/
Error: Remove workaround that adds "removed" action to "member" event
at /Users/z/git/octokit/webhooks/lib/workarounds.js:21:15
at Array.forEach (<anonymous>)
at workarounds (/Users/z/git/octokit/webhooks/lib/workarounds.js:10:12)
at checkOrUpdateWebhooks (/Users/z/git/octokit/webhooks/lib/check-or-update-webhooks.js:40:3)
```

feat: `installation.{suspend,unsuspend}`

---

index.json
lib/check-or-update-webhooks.js
lib/workarounds.js

Hey 🙂 
I've added a workaround to clear the `inputs` object in the `workflow_dispatch` event, since it does not have a fixed shape. Sorry I haven't done it [in my previous PR](https://github.com/octokit/webhooks/pull/134), somehow it hasn't caught my eye.

fix: remove sample inputs from `workflow_dispatch` webhook

---

index.json
payload-examples/api.github.com/pull_request_review.submitted.payload.json
payload-examples/api.github.com/pull_request_review_comment.created.payload.json

The pull request review payloa has an installation object as defined here: https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#pull_request_review
Adding this will end up fixing the typescript definitions

fix: add installation object to pull_request_review and pull_request_review_comment events

---

index.json
payload-examples/api.github.com/issues.assigned.payload.json
payload-examples/api.github.com/issues.locked.payload.json
payload-examples/api.github.com/issues.milestoned.payload.json
payload-examples/api.github.com/issues.opened.payload.json
payload-examples/api.github.com/issues.unlabeled.payload.json
payload-examples/api.github.com/issues.unlocked.payload.json
payload-examples/api.github.com/pull_request.assigned.payload.json
payload-examples/api.github.com/pull_request.closed.payload.json
payload-examples/api.github.com/pull_request.locked.payload.json
payload-examples/api.github.com/pull_request.opened.payload.json
payload-examples/api.github.com/pull_request.unlabeled.payload.json
payload-examples/api.github.com/pull_request.unlocked.payload.json
payload-examples/api.github.com/pull_request_review.submitted.payload.json
payload-examples/api.github.com/pull_request_review_comment.created.payload.json

Related to octokit/webhooks.js#293
This ensure all "labels" array are typed

feat: always have examples with labels

---

index.json
payload-examples/api.github.com/check_run.requested_action.payload.json

This PR adds a missing payload example for [check_run.requested_action](https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#check_run). I copied existing approaches from the repo but please let me know if i'm missing anything!
cc @gr2m

fix: add missing example for check_run.requested_action

---

package.json

This ensures that the default prettier settings are used for this repo - i.e I've got [my default `.prettierrc`](https://github.com/ackama/prettier-config-ackama) in my home directory, which means without this in the repo running prettier uses that.

chore: add prettier config

---

package-lock.json
package.json

Prettier is not used by this project at "runtime", so it's only needed for deving.

fix(deps): move `prettier` to `devDependencies`

---

bin/format-with-prettier.ts

This is the script that made #260
The backstory is that while `prettier` formats things consistently, with objects you can "choose" if they're on a single line or not based on if you put a newline after the opening brace - while I think this is a great thing, this is a rare case where we don't want that since such newlines are lost when you parse raw json into js objects, meaning noisy diffs when you're working with scripts and especially when you're wanting to compare two versions of schemas to check if the output is what you're wanting or if you've messed something up.
I'm on the fence about making this script "required", as it takes a few seconds to run since you're reading in every json file formatting and then writing them again, and it's not something I'm expecting to pop up …

chore: add script for formatting schemas & payloads with `prettier`

---

bin/validate-payload-examples.ts

Fixes #250
I figured there's some use in either behaviour depending on what the actual error is, and defaulted to exiting at the first error as that'll make it less explody when you're not expecting an error (since i.e it could be a strict-mode error in one of the common schemas, so every schema that uses it will throw).

chore: improve validation script

---

payload-schemas/schemas/issues/unpinned.schema.json

Technically we could probably set `maxItems` to 15 since iirc thats the current limit in GH, but there's not a lot of value.
This will let us enable strictMode in ajv 🎉

fix: don't validate array as a tuple

---

bin/optimize-schemas.ts
payload-schemas/schemas/common/repository.schema.json
payload-schemas/schemas/fork/event.schema.json
payload-schemas/schemas/public/event.schema.json
payload-schemas/schemas/repository/archived.schema.json
payload-schemas/schemas/repository/privatized.schema.json
payload-schemas/schemas/repository/publicized.schema.json
payload-schemas/schemas/repository/unarchived.schema.json

Reverts part of #271, and removed the implementation of that optimization - I'll be landing a better one that merges just `null` straight afterwards.
The reason for the revert is that while its an optimization on paper, it's considered [not strict by ajv](https://github.com/ajv-validator/ajv/blob/master/docs/strict-mode.md#strict-types) due to it being a confusing union, which I agree with.

fix: unmerge union of types that are not null

---

bin/ref-common-schemas.ts
package.json
payload-schemas/schemas/check_run/completed.schema.json
payload-schemas/schemas/check_run/created.schema.json
payload-schemas/schemas/check_run/requested_action.schema.json
payload-schemas/schemas/check_run/rerequested.schema.json
payload-schemas/schemas/check_suite/completed.schema.json
payload-schemas/schemas/check_suite/requested.schema.json
payload-schemas/schemas/check_suite/rerequested.schema.json
payload-schemas/schemas/common/repo-ref.schema.json
schema.d.ts

Here it is - the `ref-common-schemas` script.
It loads all the schemas in `common`, and compares every value of every key in every schema against those schemas to see if they match, and if they do it replaces them with a reference to the matched common schema.
Before comparing, the script attempts to normalize the values as best it can by removing common "meta" keys (such as `description`), sorting all arrays so they're always in the same order, and ensuring `type` is always an array.
The script also accounts for `null` unions: before comparing a value to the common schemas, it checks if `type` includes `"null"` - if it does then the value is "split" into a tuple of the type without null and `{ "type": "null" }`. The comparison is then done against the "type without null" and if they're …

feat: create `repo-ref` common schema

---

README.md
bin/octokit-types.ts
schema.d.ts

I think this name makes much more sense as it's literally what it is, but I've kept the original `Schema` type as then it's technically not breaking & matches closer to the fact that it's typing `schema.json` 🤷

feat: export `WebhookEvent` type

---

bin/octokit-types.ts
schema.d.ts

Just so that things are nice and consistent

feat: generate `WebhookEventMap` & `WebhookEventName` type aliases

---

bin/extract-common-schema.ts
payload-schemas/schemas/common/sponsorship-tier.schema.json
payload-schemas/schemas/sponsorship/cancelled.schema.json
payload-schemas/schemas/sponsorship/created.schema.json
payload-schemas/schemas/sponsorship/edited.schema.json
payload-schemas/schemas/sponsorship/pending_cancellation.schema.json
payload-schemas/schemas/sponsorship/pending_tier_change.schema.json
payload-schemas/schemas/sponsorship/tier_changed.schema.json
schema.d.ts

Ok this one I'm pretty proud of - because it takes far too much time to copy a JSON schema into its own file, I made a script to do it.
Here's what you do:
* look over `schema.d.ts` and notice a property with an object type that's repeated a few times
* run `scripts/extract-common-schema.ts <name of the interface that has the property>.<dot-path to the property> <name of the interface that the common schema should generate>`
* i.e for this commit I did `bin/extract-common-schema.ts SponsorshipEditedEvent.sponsorship.tier SponsorshipTier`
* run `scripts/ref-common-schemas.ts` to have all instances of that schema in the payload schemas replaced with a ref to your new common schema
* commit the results
* ???
* profit

Create common schema extractor

---

bin/extract-common-schema.ts
bin/ref-common-schemas.ts

Not having them print anything at all made me a little eh when running my `script.sh`:
```
#!/usr/bin/env bash
set -e
bin/extract-common-schema.ts "$@"
bin/ref-common-schemas.ts
npm run --silent build:schema
npm run --silent build:types
```
As I had no idea what it was doing until it reached the `npm run`s.
Also added basic flag support to the extractor script to allow overwriting existing files if desired.

Adjust scripts

---

payload-schemas/schemas/check_suite/completed.schema.json
payload-schemas/schemas/check_suite/requested.schema.json
payload-schemas/schemas/check_suite/rerequested.schema.json
payload-schemas/schemas/common/committer.schema.json
payload-schemas/schemas/push/event.schema.json
payload-schemas/schemas/workflow_run/completed.schema.json
payload-schemas/schemas/workflow_run/requested.schema.json
schema.d.ts

I suspect these might have some optional fields, namely `date` & `username` as there are other instances of this structure but with extra fields.
i.e.
* `StatusEvent.commit.commit` has the same `author` and `committer` properties as `Committer` but with a `date` field too
* `PushEvent.commits` has the same `author` and `committer` properties as `Committer` but with a `username` field too
Would be cool if someone could check if it's our payloads that are outdated.

feat: create `Committer` common schema

---

payload-schemas/schemas/marketplace_purchase/pending_change.schema.json
payload-schemas/schemas/marketplace_purchase/pending_change_cancelled.schema.json
schema.d.ts

feat: add `pending_change` and `cancelled_pending_change`

---

bin/ref-common-schemas.ts

It makes total sense in hindsight: the replacer gets passed *references* to the properties of the object being stringified, meaning actions on objects and arrays mutate the original schema.
This means currently `ref-common-schema` will end up modifying our schemas even if it doesn't update anything to reference a common schema.
This currently doesn't actually occur as we've already optimized, but making this change now because it's cheap and might as well :)
Also, realised that doing `key === 'type'` is silly because we have schemas that have a property called `type` - while they still will match because we're turning *all* instances of that property into an array, I've adjusted the script to be more correct anyway.

chore: clone schemas before normalizing & improve `type` property check

---

bin/diff-interface-schemas.ts

This is so very useful in hunting down subtle type differences 🎉 
```
webhooks on  master is 📦 v0.0.0-development
❯ bin/diff-interface-schemas.ts Milestone IssueCommentDeletedEvent.issue.milestone
{
properties: {
state: {
-      enum: [
-        "closed"
-        "open"
-      ]
}
due_on: {
type: [
-        "null"
"string"
]
}
closed_at: {
type: [
-        "null"
"string"
]
}
}
}
```

chore: create `diff-interface-schema` script

---

bin/octokit-types.ts
payload-schemas/index.ts
payload-schemas/schemas/common/simple-pull-request.schema.json
payload-schemas/schemas/issue_comment/deleted.schema.json
payload-schemas/schemas/issue_comment/edited.schema.json
payload-schemas/schemas/milestone/closed.schema.json
payload-schemas/schemas/milestone/created.schema.json
payload-schemas/schemas/milestone/opened.schema.json
schema.d.ts

When present, `tsAdditionalProperties` is used as the value for `additionalProperties` only when compiling a given schema to TypeScript, which allows us to use `allOf` to "extend" a common schema without weakening our types.
This is required because we have to allow additionalProperties in the extending schema type (the schema in index `1` of the `allOf` array) since it's only a subset of the properties defined in the parent schema. However if `additionalProperties` is not set to `false` when generating the types it adds `[key: string]: unknown`, which makes the type an open object which is incorrect.
The drive behind this is that ideally the common schemas/types should represent the *general* state of a particular type rather than the state of the type for only a specific subset of …

fix: improve usage of `milestone` common schema

---

payload-schemas/schemas/issue_comment/deleted.schema.json
payload-schemas/schemas/issue_comment/edited.schema.json
schema.d.ts

Originally this was just marking `milestone` as possibly `null`, but then I realised that there isn't a reason why `description`, `due_on`, or `closed_at` should never be `null` for the events in question.

fix: mark `milestone` property as possibly `null` on `issue_comment`

---

payload-schemas/schemas/common/simple-pull-request.schema.json
schema.d.ts

Ideally I'd like to combine this with `pull-request`, but it'll need some extra work to make the types come out nice.
The best way to do that'll probably be to make this schema `pull-request` w/ all the properties, and then rename the other to `pull-request-complete` as an `allOf` of this + the extra properties being marked as required 🤔

fix: update schema for `milestone` property on `simple-pull-request`

---

bin/diff-interface-schemas.ts
bin/extract-common-schema.ts
bin/format-with-prettier.ts
bin/octokit-schema.ts
bin/octokit-types.ts
bin/optimize-schemas.ts
bin/ref-common-schemas.ts
bin/utils/argv.ts
bin/utils/forEachJsonFile.ts
bin/utils/getSchemaFromPath.ts
bin/utils/index.ts
bin/utils/loadMapOfSchemas.ts
bin/utils/misc.ts
bin/utils/normalizeSchema.ts
bin/validate-payload-examples.ts

Have I gone a little overboard? Maybe
Have I got a follow-up PR refactoring argv parsing that's probably overboard? Yup 😁
Does it have `--help` doc support? 💯
----
This does what it says in the title - the majority of the refactoring is moving things into `utils/` wholesale, with a sprinkle of name and code refactoring based on reducing duplication and such.

refactor: move common functions in bin scripts into utils folder

---

index.json
payload-examples/api.github.com/code_scanning_alert/reopened.payload.json
payload-examples/api.github.com/code_scanning_alert/reopened.with-organization.payload.json
payload-schemas/schemas/code_scanning_alert/appeared_in_branch.schema.json
payload-schemas/schemas/code_scanning_alert/created.schema.json
payload-schemas/schemas/code_scanning_alert/fixed.schema.json
payload-schemas/schemas/code_scanning_alert/reopened.schema.json
schema.d.ts

Hi there 👋 
I'm from the codescanning Team at GitHub and we're doing a slight update. Previously:
sender | object | If the action is reopened_by_user or closed_by_user, the sender object will be the user that triggered the event. The sender object is empty for all other actions.
-- | -- | --
See here for more info: https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#code_scanning_alert
Now, we'll include a default sender object instead of having that field be empty. 
We basically want to update the payload schemas to look like the `closed_by_user` schema by having the sender field be required, so we're just adding two lines of code to all the schemas in the code-scanning-alert folder:
1. https://github.com/octokit/webhooks/blob/03b633b2aed02709c55e3df89774 …

Update Codescanning Alert Payload Schemas to Include a Sender Field

---

payload-schemas/schemas/issues/assigned.schema.json
payload-schemas/schemas/issues/closed.schema.json
payload-schemas/schemas/issues/deleted.schema.json
payload-schemas/schemas/issues/demilestoned.schema.json
payload-schemas/schemas/issues/edited.schema.json
payload-schemas/schemas/issues/labeled.schema.json
payload-schemas/schemas/issues/locked.schema.json
payload-schemas/schemas/issues/milestoned.schema.json
payload-schemas/schemas/issues/opened.schema.json
payload-schemas/schemas/issues/pinned.schema.json
payload-schemas/schemas/issues/reopened.schema.json
payload-schemas/schemas/issues/transferred.schema.json
payload-schemas/schemas/issues/unassigned.schema.json
payload-schemas/schemas/issues/unlabeled.schema.json
payload-schemas/schemas/issues/unlocked.schema.json
payload-schemas/schemas/issues/unpinned.schema.json
payload-schemas/schemas/pull_request/assigned.schema.json
payload-schemas/schemas/pull_request/closed.schema.json
payload-schemas/schemas/pull_request/converted_to_draft.schema.json
payload-schemas/schemas/pull_request/edited.schema.json
payload-schemas/schemas/pull_request/labeled.schema.json
payload-schemas/schemas/pull_request/locked.schema.json
payload-schemas/schemas/pull_request/opened.schema.json
payload-schemas/schemas/pull_request/ready_for_review.schema.json
payload-schemas/schemas/pull_request/reopened.schema.json
payload-schemas/schemas/pull_request/synchronize.schema.json
payload-schemas/schemas/pull_request/unassigned.schema.json
payload-schemas/schemas/pull_request/unlabeled.schema.json
payload-schemas/schemas/pull_request/unlocked.schema.json
schema.d.ts

* Removes the `label` property from other actions then then `labeled` and `unlabeled`
* Removes the `assignees` property from all schemas, it doesn't exist at the top level
* Removes the `assignee` property from other actions then then `assigned` and `unassigned`

fix: cleanup properties in issues and pull_request schemas

---

payload-schemas/schemas/secret_scanning_alert/created.schema.json
schema.d.ts

According to the docs, the sender property is empty for the `created` action

fix: remove sender property from SecretScanningAlertCreatedEvent

---

index.json
payload-examples/api.github.com/push/1.payload.json
payload-schemas/schemas/push/event.schema.json

Found this when reviewing webhook calls this morning.

fix: remove `format` from `compare` property on `push` payload schema

---

payload-schemas/schemas/issue_comment/edited.schema.json
schema.d.ts

An issue can be edited after it has been closed, therefore this override is unnecessary

fix: remove `null` override on `IssueCommentEditedEvent#issue.closed_at`

---

bin/octokit-types.ts
schema.d.ts

Following on from my comment [here](https://github.com/octokit/webhooks/pull/323#issuecomment-808949949), I realised we can do this instead 🎉 
`json-schema-to-typescript` will pull a `$ref` with a description out into its own interface, duplicating it with a number suffix which makes things confusing.

fix: remove `description` from objects with `$ref` to stop duplication

---

README.md
bin/octokit-schema.ts
bin/validate-schema.ts
package.json

When you include `$id`, it affects how `$ref` is resolved - this is fine in some cases, but not others (I don't know the exact specifics, other than it seems to be a relative vs absolute style problem).
You can see the break with this schema:
```
{
"$schema": "http://json-schema.org/draft-07/schema#",
"definitions": {
"s$1": {
"$id": "s$1",
"type": "object",
"properties": { "p": { "$ref": "#/definitions/s$2" } }
},
"s$2": {
"$id": "#/definitions/s$2",
"type": "object"
}
},
"oneOf": [{ "$ref": "#/definitions/s$1" }]
}
```
We don't actually need the IDs in our schema, so we can safely just drop them.
----
Fixes #429

fix: don't include `$id` property in compiled schema

---

package.json

Since we don't publish this package anymore, and it's only used to store the scripts and dependencies, I removed the `files` entry and marked the package as private

chore: cleanup un-needed entries in the root `package.json` and mark it as private

---

payload-examples/index.d.ts

The examples property is an Array of `WebhookEventMap[TName]` but it wasn't marked as so

fix(types): mark `WebhookDefinition#examples` to be an `Array`

---

README.md
payload-types/README.md

The link to the generated `payload-examples` JSON was only updated in one
place. But the `payload-types` README still referenced the old URL. This
commit updates that URL throughout this repositories README's.

fix(readme): Definition links in README's where 404ing

---

.github/workflows/prettier.yml

This should avoid errors like this:
Not sure if there is a more elegant way but this should work

ci(prettier): fail git commit silently

---

cache/api.github.com/webhook-events-and-payloads.html
cache/ghes-221/webhook-events-and-payloads.html
cache/ghes-222/webhook-events-and-payloads.html
cache/ghes-30/webhook-events-and-payloads.html
cache/ghes-31/webhook-events-and-payloads.html
cache/github.ae/webhook-events-and-payloads.html
lib/get-html.ts
payload-examples/api.github.com/index.json
payload-examples/api.github.com/package/published.payload.json
payload-examples/github.ae/index.json
payload-schemas/api.github.com/package/published.schema.json
payload-schemas/api.github.com/package/updated.schema.json
payload-types/schema.d.ts

GitHub refactored the docs and moved the HTML we want out of that ID. It is another layer down compared to before
closes #513

fix(api.github.com): add new properties for the Container registry

---

.github/workflows/prettier.yml
.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/update-prettier.yml
.github/workflows/update.yml

Add `cache` to workflows using `actions/setup-node`
`setup-node` GitHub Action just released a new option to add cache to steps using it.
You can find the details here: https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/
---
🤖 This PR has been generated automatically by [this octoherd script](https://github.com/oscard0m/octoherd-script-add-cache-to-node-github-action), feel free to run it in your GitHub user/org repositories! 💪🏾

ci(workflow): add cache to workflows using actions/setup-node

---

payload-schemas/api.github.com/issues/labeled.schema.json
payload-schemas/api.github.com/issues/unlabeled.schema.json

If I understand it correctly, the `issues.labeled` event only adds a label. If a label is removed, the action is set `unlabeled`. Or am I missing something?

fix(api.github.com): update descriptions for `issues.labeled` and `issues.unlabeled` events

---

payload-schemas/api.github.com/code_scanning_alert/closed_by_user.schema.json

Type the enum array lists `null`, it's not a valid value per the `type` field. Note that this is the only instance where `enum` contains `null` and `type` does not:
```
$ git ls-files | grep schema.json | xargs -L1 jq -c '.. | select(.enum?) | select(.enum | index(null) != null) | .type' 
["string","null"]
["string","null"]
["string","null"]
["string","null"]
["string","null"]
["string","null"]
["string","null"]
["string","null"]
["string","null"]
["string","null"]
["string","null"]
["string","null"]
["string","null"]
["string","null"]
["string","null"]
"string"
["string","null"]
["string","null"]
["string","null"]
["string","null"]
["string","null"]
["string","null"]
["string","null"]
["string","null"]
["string","null"]
["string","null"]
["string","null"]
["string","null"] …
```

fix(schema): add `null` to `type` field where missing when present in `enum`

---

lib/get-html.ts
package-lock.json
package.json

will hopefull work around build errors such as
https://github.com/octokit/webhooks/runs/4486395928\?check_suite_focus\=true\#step:7:39
I see these build errors occur several time each day, it's creating quite some noise in my notifications

refactor: use `got` with retries instead of `@octokit/request` to retrieve the docs HTML pages

---

CONTRIBUTING.md

These are basic steps to creating a schema.
Fixes #643

docs(CONTRIBUTING): add section on how to create schemas

---

payload-schemas/api.github.com/common/workflow-job.schema.json
payload-schemas/api.github.com/workflow_job/queued.schema.json
payload-types/schema.d.ts

My personal code generation tool led me to notice a missing refactor for the `queued` variant of the `workflow_job` event. Am refactoring it here along the same lines as what is used for other variants of the same event.
This does require the relaxation of the `minItems` constraints on the `steps` field in the refactored Workflow Job spec and hence results in a slight alteration of the validation semantics of the other event variants, without it being a breaking change.
If someone could point out a way to forgo this constraint relaxation I am all ears but I did try to add an override for `steps` alongside the `status` one within the `queued` spec but this resulted in test failures.
Example, adding the following in `queued.schema.json`:
```json
{
"type": "object",
"required": ["status"], …
```

fix: refactor `workflow_job.queued` event to use the `WorkflowJob` common shema

---

.github/renovate.json
package.json

Putting the configuration in the `package.json` is deprecated

ci(renovate): move configuaration out of `package.json`

---

payload-schemas/api.github.com/common/commit.schema.json
payload-types/schema.d.ts

This PR applies the description changes detected in #691 to the schemas. They were automatically applied to the examples, but I forgot to make the manual schema changes.

fix: update schema descriptions for `added`, `removed` and `modified` files in `commits`

---

payload-schemas/api.github.com/branch_protection_rule/edited.schema.json
payload-schemas/api.github.com/common/branch-protection-rule-array.schema.json
payload-schemas/api.github.com/common/branch-protection-rule-boolean.schema.json
payload-schemas/api.github.com/common/branch-protection-rule-enforcement-level.schema.json
payload-schemas/api.github.com/common/branch-protection-rule-number.schema.json
payload-schemas/api.github.com/common/branch-protection-rule.schema.json
payload-types/schema.d.ts

https://github.com/octokit/webhooks/issues/689#issuecomment-1211422677

fix: refactor `BranchProtectionRule` to have a common schema for the different rule types

---

payload-schemas/api.github.com/secret_scanning_alert/resolved.schema.json
payload-types/schema.d.ts

Resolves #806 
Makes the resolved schema consistent with the schema it inherits from ( https://github.com/octokit/webhooks/blob/a5c455c39903cfc033d4c7a0ee0dc6476aa60a2d/payload-schemas/api.github.com/common/secret-scanning-alert.schema.json#L61 ) 
Bugfix: Type: Bug

Update wont_fix typo in secret_scanning_alert

---

.github/workflows/prettier.yml
.github/workflows/test.yml
.github/workflows/update-prettier.yml
.github/workflows/update.yml

While this change is not technically required as part of our efforts to [drop support for NodeJS v14, v16](https://github.com/orgs/octokit/discussions/44) - this does help to get all of our packages and tooling in sync with a consistent node version. 
Part of: https://github.com/octokit/octokit.js/issues/2486
---
- We were using node v16 in our test workflow
- We are now using v18

build(deps): updates all node versions in workflows to v18

---

payload-schemas/api.github.com/common/auto-merge.schema.json
payload-types/schema.d.ts

See: https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request
Resolves #828
----
* The properties `enabled_by`, `commit_title` and `commit_message` did not allow null
* The properties `enabled_by`, `commit_title` and `commit_message` are nullable
----

fix: declare pull_request auto_merge properties as string|null

---

payload-schemas/api.github.com/common/workflow-step-completed.schema.json
payload-types/schema.d.ts

Resolves #891 
----
* Workflow steps with status "completed" CAN'T have a "cancelled" conclusion.
* Workflow steps with status "completed" CAN have a "cancelled" conclusion.
----

Add "cancelled" as possible conclusion of a completed workflow step

---

payload-schemas/api.github.com/merge_group/destroyed.schema.json
payload-types/schema.d.ts

* The schema for the `merge_group` [destroyed](https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=destroyed#merge_group) event was not present.
* The schema for the `merge_group` destroyed event is present.
----

feat(schemas): added schema for the `merge_group` destroyed event

---

payload-examples/api.github.com/discussion/answered.payload.json
payload-examples/api.github.com/discussion/category_changed.payload.json
payload-examples/api.github.com/discussion/created.payload.json
payload-examples/api.github.com/discussion/edited.payload.json
payload-examples/api.github.com/discussion/edited.with-reactions.payload.json
payload-examples/api.github.com/discussion/labeled.payload.json
payload-examples/api.github.com/discussion/labeled.with-reactions.payload.json
payload-examples/api.github.com/discussion/locked.payload.json
payload-examples/api.github.com/discussion/locked.with-reactions.payload.json
payload-examples/api.github.com/discussion/pinned.payload.json
payload-examples/api.github.com/discussion/transferred.payload.json
payload-examples/api.github.com/discussion/unanswered.payload.json
payload-examples/api.github.com/discussion/unlabeled.payload.json
payload-examples/api.github.com/discussion/unlocked.payload.json
payload-examples/api.github.com/discussion_comment/created.payload.json
payload-examples/api.github.com/discussion_comment/deleted.payload.json
payload-examples/api.github.com/discussion_comment/edited.payload.json
payload-schemas/api.github.com/common/discussion-category.schema.json
payload-schemas/api.github.com/common/discussion.schema.json
payload-schemas/api.github.com/discussion/category_changed.schema.json
payload-types/schema.d.ts

Resolves #959 
----
`$.category.node_id` is missing
`$.category.node_id` is defined with type `string`
----

discussion-comment: add missing property `category.node_id`
